query PurchaseOrder($request: PurchaseOrderRequest!) {
	purchaseOrder(request: $request) {
		...PurchaseOrderFields
		items {
			...PurchaseOrderItemFields
		}
		purchaseInvoices {
			...PurchaseInvoiceFields
		}
		receiptNotes {
			...ReceiptNoteFields
		}
	}
}

