fragment PurchaseOrderFields on PurchaseOrder {
  uuid
  code
  status
  receiptStatus
  billingStatus
  supplierUuid
  supplierName
  supplierAddress
  totalAmount
  paidAmount
  remainingAmount
  totalQty
  receivedQty
  remainingQty
  insertedAt
  updatedAt
}

