fragment SalesOrderFields on SalesOrder {
  uuid
  code
  status
  billingStatus
  deliveryStatus
  customerName
  totalAmount
  paidAmount
  remainingAmount
  totalQty
  deliveredQty
  remainingQty
  insertedAt
  updatedAt
}

